- template:
    src: hdfs-namenode.service.j2
    dest: /etc/systemd/system/hdfs-namenode.service

- name: enable hdfs-namenode service
  service:
    name: hdfs-namenode
    enabled: yes
    state: started

- template: 
    src: yarn-resourcemanager.service.j2
    dest: /etc/systemd/system/yarn-resourcemanager.service

- name: enable yarn-resourcemanager service 
  service:
    name: yarn-resourcemanager
    enabled: yes
    state: started
