---

- user:
    name: "{{ user }}"
    comment: "User for hadoop process" 
    shell: /bin/bash
    password: "{{ password  | password_hash('sha512') }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa


